version: "2.3"
services:

  sfmt_dev:
    container_name: sfmt_dev
    build: .
    working_dir: /development
    runtime: nvidia
    environment:
      - DISPLAY
    ipc: host # for GUI
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # for GUI access
      - .:/development
    #command: python -u dev.py
